[pwsh7]
repo = "https://github.com/BryanHeBY/mant-pwsh-docs.git"
branch = "main"
path = "docs/en-US/pwsh7"
priority = 20

[pwsh51]
repo = "https://github.com/BryanHeBY/mant-pwsh-docs.git"
branch = "main"
path = "docs/en-US/pwsh51"
priority = 10

[windows-tools]
repo = "https://github.com/BryanHeBY/mant-pwsh-docs.git"
branch = "main"
path = "docs/en-US/windows-tools"
priority = 5

[cross-platform-tools]
repo = "https://github.com/BryanHeBY/mant-pwsh-docs.git"
branch = "main"
path = "docs/en-US/cross-platform-tools"
priority = -5
